name: Come Tao My Bao
favicon: null
layout_spectrum: 0.60822
typography_spectrum: 0.12717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b36c20'
    - '#fc491e'
    - '#fedc38'
    - '#231f20'
    - '#ff0000'
  brandStrength: 0.6074360203929245
  lightness: 1
  saturation: 0.5366267557255924
  rhythmicContrast: 0.28807613044045866
purpose: []
